// <auto-generated />
using System;
using FormManagement.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace FormManagement.Infrastructure.Migrations
{
    [DbContext(typeof(FormManagementDbContext))]
    [Migration("20260513024335_InitFormManagement_Oracle")]
    partial class InitFormManagement_Oracle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FormManagement.Domain.DocumentTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedTraceId")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("created_trace_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("deleted_by");

                    b.Property<byte[]>("DocxBytes")
                        .HasColumnType("BLOB")
                        .HasColumnName("docx_bytes");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("name");

                    b.Property<string>("SfdtContent")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("sfdt_content");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("updated_by");

                    b.Property<string>("UsedFieldsJson")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("used_fields_json");

                    b.Property<int>("Version")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_templates");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_templates_category");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_templates_code");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_templates_status");

                    b.ToTable("templates", (string)null);
                });

            modelBuilder.Entity("FormManagement.Domain.MetadataDef", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedTraceId")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("created_trace_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("description");

                    b.Property<string>("FieldGroup")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("field_group");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("label");

                    b.Property<int>("Type")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("updated_by");

                    b.Property<string>("ValidationJson")
                        .HasColumnType("CLOB")
                        .HasColumnName("validation_json");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_metadata");

                    b.HasIndex("FieldGroup")
                        .HasDatabaseName("ix_metadata_field_group");

                    b.HasIndex("Value")
                        .IsUnique()
                        .HasDatabaseName("ix_metadata_value");

                    b.ToTable("metadata", (string)null);
                });

            modelBuilder.Entity("FormManagement.Domain.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedTraceId")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("created_trace_id");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("data_json");

                    b.Property<int>("ExportFormat")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("export_format");

                    b.Property<string>("OutputPath")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("output_path");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("template_id");

                    b.Property<int>("TemplateVersion")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("template_version");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_submissions");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("ix_submissions_template_id");

                    b.ToTable("submissions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
