// <auto-generated />
using System;
using IssueLink.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace IssueLink.Infrastructure.Migrations
{
    [DbContext(typeof(IssueLinkDbContext))]
    [Migration("20260505080023_InitIssueLink_Oracle")]
    partial class InitIssueLink_Oracle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IssueLink.Domain.IssueLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedTraceId")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("created_trace_id");

                    b.Property<int>("LinkType")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("link_type");

                    b.Property<Guid>("SourceIssueId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("source_issue_id");

                    b.Property<Guid>("SourceProjectId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("source_project_id");

                    b.Property<Guid>("TargetIssueId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("target_issue_id");

                    b.Property<Guid>("TargetProjectId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("target_project_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_issue_links");

                    b.HasIndex("SourceIssueId")
                        .HasDatabaseName("ix_issue_links_source_issue_id");

                    b.HasIndex("TargetIssueId")
                        .HasDatabaseName("ix_issue_links_target_issue_id");

                    b.HasIndex("SourceIssueId", "TargetIssueId", "LinkType")
                        .IsUnique()
                        .HasDatabaseName("ix_issue_links_source_issue_id_target_issue_id_link_type");

                    b.ToTable("issue_links", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
