// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notification.Infrastructure;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Notification.Infrastructure.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    [Migration("20260505073830_InitNotification_Oracle")]
    partial class InitNotification_Oracle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Notification.Domain.EmailLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id");

                    b.Property<string>("ArgsJson")
                        .HasColumnType("CLOB")
                        .HasColumnName("args_json");

                    b.Property<string>("BodyPreview")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("body_preview");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedTraceId")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("created_trace_id");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("error");

                    b.Property<string>("Provider")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)")
                        .HasColumnName("provider_message_id");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("sent_at");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("status");

                    b.Property<string>("SubjectRendered")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("NVARCHAR2(512)")
                        .HasColumnName("subject_rendered");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)")
                        .HasColumnName("template_key");

                    b.Property<string>("ToEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("NVARCHAR2(320)")
                        .HasColumnName("to_email");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_email_logs");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_email_logs_status_created_at");

                    b.HasIndex("TemplateKey", "CreatedAt")
                        .HasDatabaseName("ix_email_logs_template_key_created_at");

                    b.HasIndex("ToEmail", "CreatedAt")
                        .HasDatabaseName("ix_email_logs_to_email_created_at");

                    b.ToTable("email_logs", (string)null);
                });

            modelBuilder.Entity("Notification.Domain.EmailTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedTraceId")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("created_trace_id");

                    b.Property<string>("HtmlBodyTemplate")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("html_body_template");

                    b.Property<int>("IsEnabled")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)")
                        .HasColumnName("name");

                    b.Property<string>("SubjectTemplate")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("NVARCHAR2(512)")
                        .HasColumnName("subject_template");

                    b.Property<string>("TextBodyTemplate")
                        .HasColumnType("CLOB")
                        .HasColumnName("text_body_template");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_email_templates");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_email_templates_key");

                    b.ToTable("email_templates", (string)null);
                });

            modelBuilder.Entity("Notification.Domain.InAppNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedTraceId")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("created_trace_id");

                    b.Property<int>("IsRead")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("is_read");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("payload_json");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("recipient_user_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_in_app_notifications");

                    b.HasIndex("RecipientUserId", "CreatedAt")
                        .HasDatabaseName("ix_in_app_notifications_recipient_user_id_created_at");

                    b.HasIndex("RecipientUserId", "IsRead")
                        .HasDatabaseName("ix_in_app_notifications_recipient_user_id_is_read");

                    b.ToTable("in_app_notifications", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
