// <auto-generated />
using System;
using Issue.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Issue.Infrastructure.Migrations
{
    [DbContext(typeof(IssueDbContext))]
    [Migration("20260505084143_InitIssue_Oracle")]
    partial class InitIssue_Oracle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Issue.Domain.Issue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("assignee_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedTraceId")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("created_trace_id");

                    b.Property<Guid>("CurrentStatusId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("current_status_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasColumnType("CLOB")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("due_date");

                    b.Property<int>("IsArchived")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("is_archived");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("IssueTypeId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("issue_type_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("key");

                    b.Property<string>("Labels")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("labels");

                    b.Property<int>("Number")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("number");

                    b.Property<int?>("OriginalEstimateMinutes")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("original_estimate_minutes");

                    b.Property<Guid?>("ParentIssueId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("parent_issue_id");

                    b.Property<int>("Priority")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("priority");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("project_id");

                    b.Property<int?>("RemainingEstimateMinutes")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("remaining_estimate_minutes");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("reporter_id");

                    b.Property<decimal?>("StoryPoints")
                        .HasPrecision(12, 2)
                        .HasColumnType("DECIMAL(12,2)")
                        .HasColumnName("story_points");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("summary");

                    b.Property<int?>("TimeSpentMinutes")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("time_spent_minutes");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id")
                        .HasName("pk_issues");

                    b.HasIndex("AssigneeId")
                        .HasDatabaseName("ix_issues_assignee_id");

                    b.HasIndex("CurrentStatusId")
                        .HasDatabaseName("ix_issues_current_status_id");

                    b.HasIndex("IssueTypeId")
                        .HasDatabaseName("ix_issues_issue_type_id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_issues_key");

                    b.HasIndex("ParentIssueId")
                        .HasDatabaseName("ix_issues_parent_issue_id");

                    b.HasIndex("ReporterId")
                        .HasDatabaseName("ix_issues_reporter_id");

                    b.HasIndex("ProjectId", "Number")
                        .HasDatabaseName("ix_issues_project_id_number");

                    b.ToTable("issues", (string)null);
                });

            modelBuilder.Entity("Issue.Domain.IssueWatcher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("added_at");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("issue_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_issue_watchers");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_issue_watchers_user_id");

                    b.HasIndex("IssueId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_issue_watchers_issue_id_user_id");

                    b.ToTable("issue_watchers", (string)null);
                });

            modelBuilder.Entity("Issue.Domain.SavedFilter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedTraceId")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("created_trace_id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("description");

                    b.Property<int>("IsShared")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("is_shared");

                    b.Property<string>("Jql")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("jql");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("owner_user_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_saved_filters");

                    b.HasIndex("IsShared")
                        .HasDatabaseName("ix_saved_filters_is_shared");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_saved_filters_owner_user_id");

                    b.ToTable("saved_filters", (string)null);
                });

            modelBuilder.Entity("Issue.Domain.IssueWatcher", b =>
                {
                    b.HasOne("Issue.Domain.Issue", null)
                        .WithMany("Watchers")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_watchers_issues_issue_id");
                });

            modelBuilder.Entity("Issue.Domain.Issue", b =>
                {
                    b.Navigation("Watchers");
                });
#pragma warning restore 612, 618
        }
    }
}
