// <auto-generated />
using System;
using CustomField.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CustomField.Infrastructure.Migrations
{
    [DbContext(typeof(CustomFieldDbContext))]
    partial class CustomFieldDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("custom_field")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CustomField.Domain.CustomField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("config_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedTraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_trace_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsSearchable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_searchable");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_custom_fields");

                    b.HasIndex("IsSystem")
                        .HasDatabaseName("ix_custom_fields_is_system");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_custom_fields_key")
                        .HasFilter("is_deleted = false");

                    b.ToTable("custom_fields", "custom_field");
                });

            modelBuilder.Entity("CustomField.Domain.CustomFieldContext", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CustomFieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("custom_field_id");

                    b.Property<string>("DefaultValueJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("default_value_json");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_global");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("IssueTypeIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("issue_type_ids");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ProjectIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("project_ids");

                    b.HasKey("Id")
                        .HasName("pk_custom_field_contexts");

                    b.HasIndex("CustomFieldId")
                        .HasDatabaseName("ix_custom_field_contexts_custom_field_id");

                    b.ToTable("custom_field_contexts", "custom_field");
                });

            modelBuilder.Entity("CustomField.Domain.CustomFieldOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CustomFieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("custom_field_id");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid?>("ParentOptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_option_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_custom_field_options");

                    b.HasIndex("CustomFieldId", "ParentOptionId", "Value")
                        .IsUnique()
                        .HasDatabaseName("ix_custom_field_options_custom_field_id_parent_option_id_value");

                    b.ToTable("custom_field_options", "custom_field");
                });

            modelBuilder.Entity("CustomField.Domain.IssueFieldValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CreatedTraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_trace_id");

                    b.Property<Guid>("CustomFieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("custom_field_id");

                    b.Property<DateTime?>("IndexedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("indexed_date");

                    b.Property<decimal?>("IndexedNumber")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("indexed_number");

                    b.Property<string>("IndexedString")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("indexed_string");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_id");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("value_json");

                    b.HasKey("Id")
                        .HasName("pk_issue_field_values");

                    b.HasIndex("CustomFieldId", "IndexedDate")
                        .HasDatabaseName("ix_issue_field_values_custom_field_id_indexed_date");

                    b.HasIndex("CustomFieldId", "IndexedNumber")
                        .HasDatabaseName("ix_issue_field_values_custom_field_id_indexed_number");

                    b.HasIndex("CustomFieldId", "IndexedString")
                        .HasDatabaseName("ix_issue_field_values_custom_field_id_indexed_string");

                    b.HasIndex("IssueId", "CustomFieldId")
                        .IsUnique()
                        .HasDatabaseName("ix_issue_field_values_issue_id_custom_field_id");

                    b.ToTable("issue_field_values", "custom_field");
                });

            modelBuilder.Entity("CustomField.Domain.CustomFieldContext", b =>
                {
                    b.HasOne("CustomField.Domain.CustomField", null)
                        .WithMany("Contexts")
                        .HasForeignKey("CustomFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_custom_field_contexts_custom_fields_custom_field_id");
                });

            modelBuilder.Entity("CustomField.Domain.CustomFieldOption", b =>
                {
                    b.HasOne("CustomField.Domain.CustomField", null)
                        .WithMany("Options")
                        .HasForeignKey("CustomFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_custom_field_options_custom_fields_custom_field_id");
                });

            modelBuilder.Entity("CustomField.Domain.CustomField", b =>
                {
                    b.Navigation("Contexts");

                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
