// <auto-generated />
using System;
using Issue.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Issue.Infrastructure.Migrations
{
    [DbContext(typeof(IssueDbContext))]
    [Migration("20260501164856_InitIssue_Postgres")]
    partial class InitIssue_Postgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("issue")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Issue.Domain.Issue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedTraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_trace_id");

                    b.Property<Guid>("CurrentStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_status_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("IssueTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_type_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("key");

                    b.Property<string>("Labels")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("labels");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<int?>("OriginalEstimateMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("original_estimate_minutes");

                    b.Property<Guid?>("ParentIssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_issue_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int?>("RemainingEstimateMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("remaining_estimate_minutes");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_id");

                    b.Property<decimal?>("StoryPoints")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("story_points");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("summary");

                    b.Property<int?>("TimeSpentMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("time_spent_minutes");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id")
                        .HasName("pk_issues");

                    b.HasIndex("AssigneeId")
                        .HasDatabaseName("ix_issues_assignee_id");

                    b.HasIndex("CurrentStatusId")
                        .HasDatabaseName("ix_issues_current_status_id");

                    b.HasIndex("IssueTypeId")
                        .HasDatabaseName("ix_issues_issue_type_id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_issues_key")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("ParentIssueId")
                        .HasDatabaseName("ix_issues_parent_issue_id");

                    b.HasIndex("ReporterId")
                        .HasDatabaseName("ix_issues_reporter_id");

                    b.HasIndex("ProjectId", "Number")
                        .HasDatabaseName("ix_issues_project_id_number");

                    b.ToTable("issues", "issue");
                });

            modelBuilder.Entity("Issue.Domain.IssueWatcher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_issue_watchers");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_issue_watchers_user_id");

                    b.HasIndex("IssueId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_issue_watchers_issue_id_user_id");

                    b.ToTable("issue_watchers", "issue");
                });

            modelBuilder.Entity("Issue.Domain.IssueWatcher", b =>
                {
                    b.HasOne("Issue.Domain.Issue", null)
                        .WithMany("Watchers")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_watchers_issues_issue_id");
                });

            modelBuilder.Entity("Issue.Domain.Issue", b =>
                {
                    b.Navigation("Watchers");
                });
#pragma warning restore 612, 618
        }
    }
}
