// <auto-generated />
using System;
using ActivityLog.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace ActivityLog.Infrastructure.Migrations
{
    [DbContext(typeof(ActivityLogDbContext))]
    [Migration("20260502034848_InitActivityLog_Oracle")]
    partial class InitActivityLog_Oracle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ActivityLog.Domain.ActivityEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedTraceId")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("created_trace_id");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("issue_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(192)
                        .HasColumnType("NVARCHAR2(192)")
                        .HasColumnName("kind");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("CLOB")
                        .HasColumnName("payload_json");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_activity_entries");

                    b.HasIndex("IssueId")
                        .HasDatabaseName("ix_activity_entries_issue_id");

                    b.HasIndex("IssueId", "OccurredAt")
                        .HasDatabaseName("ix_activity_entries_issue_id_occurred_at");

                    b.ToTable("activity_entries", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
