// <auto-generated />
using System;
using CustomField.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace CustomField.Infrastructure.Migrations
{
    [DbContext(typeof(CustomFieldDbContext))]
    [Migration("20260502034816_InitCustomField_Oracle")]
    partial class InitCustomField_Oracle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CustomField.Domain.CustomField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("config_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedTraceId")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("created_trace_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("description");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("is_deleted");

                    b.Property<int>("IsSearchable")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("is_searchable");

                    b.Property<int>("IsSystem")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("is_system");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("name");

                    b.Property<int>("Type")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_custom_fields");

                    b.HasIndex("IsSystem")
                        .HasDatabaseName("ix_custom_fields_is_system");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_custom_fields_key");

                    b.ToTable("custom_fields", (string)null);
                });

            modelBuilder.Entity("CustomField.Domain.CustomFieldContext", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id");

                    b.Property<Guid>("CustomFieldId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("custom_field_id");

                    b.Property<string>("DefaultValueJson")
                        .HasColumnType("CLOB")
                        .HasColumnName("default_value_json");

                    b.Property<int>("IsGlobal")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("is_global");

                    b.Property<int>("IsRequired")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("is_required");

                    b.Property<string>("IssueTypeIds")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("issue_type_ids");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("name");

                    b.Property<string>("ProjectIds")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("project_ids");

                    b.HasKey("Id")
                        .HasName("pk_custom_field_contexts");

                    b.HasIndex("CustomFieldId")
                        .HasDatabaseName("ix_custom_field_contexts_custom_field_id");

                    b.ToTable("custom_field_contexts", (string)null);
                });

            modelBuilder.Entity("CustomField.Domain.CustomFieldOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id");

                    b.Property<Guid>("CustomFieldId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("custom_field_id");

                    b.Property<int>("IsDisabled")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("is_disabled");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("label");

                    b.Property<int>("Order")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("order");

                    b.Property<Guid?>("ParentOptionId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("parent_option_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_custom_field_options");

                    b.HasIndex("CustomFieldId", "ParentOptionId", "Value")
                        .IsUnique()
                        .HasDatabaseName("ix_custom_field_options_custom_field_id_parent_option_id_value")
                        .HasFilter("\"parent_option_id\" IS NOT NULL");

                    b.ToTable("custom_field_options", (string)null);
                });

            modelBuilder.Entity("CustomField.Domain.IssueFieldValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id");

                    b.Property<string>("CreatedTraceId")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("created_trace_id");

                    b.Property<Guid>("CustomFieldId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("custom_field_id");

                    b.Property<DateTime?>("IndexedDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("indexed_date");

                    b.Property<decimal?>("IndexedNumber")
                        .HasPrecision(28, 8)
                        .HasColumnType("DECIMAL(28,8)")
                        .HasColumnName("indexed_number");

                    b.Property<string>("IndexedString")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("indexed_string");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("issue_id");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("value_json");

                    b.HasKey("Id")
                        .HasName("pk_issue_field_values");

                    b.HasIndex("CustomFieldId", "IndexedDate")
                        .HasDatabaseName("ix_issue_field_values_custom_field_id_indexed_date");

                    b.HasIndex("CustomFieldId", "IndexedNumber")
                        .HasDatabaseName("ix_issue_field_values_custom_field_id_indexed_number");

                    b.HasIndex("CustomFieldId", "IndexedString")
                        .HasDatabaseName("ix_issue_field_values_custom_field_id_indexed_string");

                    b.HasIndex("IssueId", "CustomFieldId")
                        .IsUnique()
                        .HasDatabaseName("ix_issue_field_values_issue_id_custom_field_id");

                    b.ToTable("issue_field_values", (string)null);
                });

            modelBuilder.Entity("CustomField.Domain.CustomFieldContext", b =>
                {
                    b.HasOne("CustomField.Domain.CustomField", null)
                        .WithMany("Contexts")
                        .HasForeignKey("CustomFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_custom_field_contexts_custom_fields_custom_field_id");
                });

            modelBuilder.Entity("CustomField.Domain.CustomFieldOption", b =>
                {
                    b.HasOne("CustomField.Domain.CustomField", null)
                        .WithMany("Options")
                        .HasForeignKey("CustomFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_custom_field_options_custom_fields_custom_field_id");
                });

            modelBuilder.Entity("CustomField.Domain.CustomField", b =>
                {
                    b.Navigation("Contexts");

                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
