// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Workflow.Infrastructure;

#nullable disable

namespace Workflow.Infrastructure.Migrations
{
    [DbContext(typeof(WorkflowDbContext))]
    partial class WorkflowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("workflow")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Workflow.Domain.IssueStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("changed_by");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comment");

                    b.Property<string>("CreatedTraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_trace_id");

                    b.Property<Guid?>("FromStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_status_id");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_id");

                    b.Property<Guid>("ToStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_status_id");

                    b.Property<Guid>("TransitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transition_id");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id")
                        .HasName("pk_issue_status_histories");

                    b.HasIndex("IssueId")
                        .HasDatabaseName("ix_issue_status_histories_issue_id");

                    b.HasIndex("IssueId", "ChangedAt")
                        .HasDatabaseName("ix_issue_status_histories_issue_id_changed_at");

                    b.ToTable("issue_status_histories", "workflow");
                });

            modelBuilder.Entity("Workflow.Domain.TransitionPostFunction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("config_json");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("TransitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transition_id");

                    b.Property<string>("TypeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type_key");

                    b.HasKey("Id")
                        .HasName("pk_transition_post_functions");

                    b.HasIndex("TransitionId", "Order")
                        .HasDatabaseName("ix_transition_post_functions_transition_id_order");

                    b.ToTable("transition_post_functions", "workflow");
                });

            modelBuilder.Entity("Workflow.Domain.TransitionRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("config_json");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("TransitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transition_id");

                    b.Property<string>("TypeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type_key");

                    b.HasKey("Id")
                        .HasName("pk_transition_rules");

                    b.HasIndex("TransitionId", "Order")
                        .HasDatabaseName("ix_transition_rules_transition_id_order");

                    b.ToTable("transition_rules", "workflow");
                });

            modelBuilder.Entity("Workflow.Domain.TransitionValidator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("config_json");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("TransitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transition_id");

                    b.Property<string>("TypeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type_key");

                    b.HasKey("Id")
                        .HasName("pk_transition_validators");

                    b.HasIndex("TransitionId", "Order")
                        .HasDatabaseName("ix_transition_validators_transition_id_order");

                    b.ToTable("transition_validators", "workflow");
                });

            modelBuilder.Entity("Workflow.Domain.Workflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedTraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_trace_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<Guid>("InitialStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("initial_status_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_template");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_workflows");

                    b.HasIndex("IsTemplate")
                        .HasDatabaseName("ix_workflows_is_template");

                    b.HasIndex("ProjectId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_workflows_project_id_key")
                        .HasFilter("is_deleted = false");

                    b.ToTable("workflows", "workflow");
                });

            modelBuilder.Entity("Workflow.Domain.WorkflowScheme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedTraceId")
                        .HasColumnType("text")
                        .HasColumnName("created_trace_id");

                    b.Property<Guid>("DefaultWorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("default_workflow_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_workflow_schemes");

                    b.HasIndex("ProjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_schemes_project_id");

                    b.ToTable("workflow_schemes", "workflow");
                });

            modelBuilder.Entity("Workflow.Domain.WorkflowSchemeItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("IssueTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_type_id");

                    b.Property<Guid>("SchemeId")
                        .HasColumnType("uuid")
                        .HasColumnName("scheme_id");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_scheme_items");

                    b.HasIndex("SchemeId", "IssueTypeId")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_scheme_items_scheme_id_issue_type_id");

                    b.ToTable("workflow_scheme_items", "workflow");
                });

            modelBuilder.Entity("Workflow.Domain.WorkflowStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<string>("Color")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("color");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_final");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_statuses");

                    b.HasIndex("WorkflowId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_statuses_workflow_id_key");

                    b.ToTable("workflow_statuses", "workflow");
                });

            modelBuilder.Entity("Workflow.Domain.WorkflowTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("FromStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_status_id");

                    b.Property<bool>("IsAutomatic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_automatic");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ScreenId")
                        .HasColumnType("uuid")
                        .HasColumnName("screen_id");

                    b.Property<Guid>("ToStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_status_id");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_transitions");

                    b.HasIndex("WorkflowId", "FromStatusId", "ToStatusId")
                        .HasDatabaseName("ix_workflow_transitions_workflow_id_from_status_id_to_status_id");

                    b.ToTable("workflow_transitions", "workflow");
                });

            modelBuilder.Entity("Workflow.Domain.TransitionPostFunction", b =>
                {
                    b.HasOne("Workflow.Domain.WorkflowTransition", null)
                        .WithMany("PostFunctions")
                        .HasForeignKey("TransitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transition_post_functions_workflow_transitions_transition_id");
                });

            modelBuilder.Entity("Workflow.Domain.TransitionRule", b =>
                {
                    b.HasOne("Workflow.Domain.WorkflowTransition", null)
                        .WithMany("Rules")
                        .HasForeignKey("TransitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transition_rules_workflow_transitions_transition_id");
                });

            modelBuilder.Entity("Workflow.Domain.TransitionValidator", b =>
                {
                    b.HasOne("Workflow.Domain.WorkflowTransition", null)
                        .WithMany("Validators")
                        .HasForeignKey("TransitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transition_validators_workflow_transitions_transition_id");
                });

            modelBuilder.Entity("Workflow.Domain.WorkflowSchemeItem", b =>
                {
                    b.HasOne("Workflow.Domain.WorkflowScheme", null)
                        .WithMany("Items")
                        .HasForeignKey("SchemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_scheme_items_workflow_schemes_scheme_id");
                });

            modelBuilder.Entity("Workflow.Domain.WorkflowStatus", b =>
                {
                    b.HasOne("Workflow.Domain.Workflow", null)
                        .WithMany("Statuses")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_statuses_workflows_workflow_id");
                });

            modelBuilder.Entity("Workflow.Domain.WorkflowTransition", b =>
                {
                    b.HasOne("Workflow.Domain.Workflow", null)
                        .WithMany("Transitions")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_transitions_workflows_workflow_id");
                });

            modelBuilder.Entity("Workflow.Domain.Workflow", b =>
                {
                    b.Navigation("Statuses");

                    b.Navigation("Transitions");
                });

            modelBuilder.Entity("Workflow.Domain.WorkflowScheme", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Workflow.Domain.WorkflowTransition", b =>
                {
                    b.Navigation("PostFunctions");

                    b.Navigation("Rules");

                    b.Navigation("Validators");
                });
#pragma warning restore 612, 618
        }
    }
}
