// <auto-generated />
using System;
using AuditLog.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace AuditLog.Infrastructure.Migrations
{
    [DbContext(typeof(AuditLogDbContext))]
    [Migration("20260505095316_InitAuditLog_Oracle")]
    partial class InitAuditLog_Oracle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuditLog.Domain.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("CLOB")
                        .HasColumnName("payload_json");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("NVARCHAR2(32)")
                        .HasColumnName("scope");

                    b.Property<Guid?>("ScopeId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("scope_id");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("trace_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_entries");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_audit_entries_actor_user_id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_audit_entries_occurred_at");

                    b.HasIndex("ScopeId")
                        .HasDatabaseName("ix_audit_entries_scope_id");

                    b.HasIndex("Action", "OccurredAt")
                        .HasDatabaseName("ix_audit_entries_action_occurred_at");

                    b.HasIndex("Scope", "OccurredAt")
                        .HasDatabaseName("ix_audit_entries_scope_occurred_at");

                    b.ToTable("audit_entries", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
