// <auto-generated />
using System;
using IssueLink.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IssueLink.Infrastructure.Migrations
{
    [DbContext(typeof(IssueLinkDbContext))]
    [Migration("20260505080000_InitIssueLink_Postgres")]
    partial class InitIssueLink_Postgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("issue_link")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IssueLink.Domain.IssueLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedTraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_trace_id");

                    b.Property<int>("LinkType")
                        .HasColumnType("integer")
                        .HasColumnName("link_type");

                    b.Property<Guid>("SourceIssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_issue_id");

                    b.Property<Guid>("SourceProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_project_id");

                    b.Property<Guid>("TargetIssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_issue_id");

                    b.Property<Guid>("TargetProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_project_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_issue_links");

                    b.HasIndex("SourceIssueId")
                        .HasDatabaseName("ix_issue_links_source_issue_id");

                    b.HasIndex("TargetIssueId")
                        .HasDatabaseName("ix_issue_links_target_issue_id");

                    b.HasIndex("SourceIssueId", "TargetIssueId", "LinkType")
                        .IsUnique()
                        .HasDatabaseName("ix_issue_links_source_issue_id_target_issue_id_link_type");

                    b.ToTable("issue_links", "issue_link");
                });
#pragma warning restore 612, 618
        }
    }
}
